### ISSUE TITLE
Premium feature request: Why?

### ISSUE THREAD

**Issue by justinbyo** [top-performers/github-bet#1]
I'm very curious to know why and how you made this bet.

![giphy](https://cloud.githubusercontent.com/assets/1707375/13167522/c2b02eb8-d688-11e5-86ca-8c1c82cbe906.gif)

**Comment by ItsMeAra** [comment]
It all started with this... http://thenextweb.com/dd/2016/02/04/reports-indicate-github-is-having-major-issues-regarding-the-companys-future/

**Comment by i-a-n** [comment]
All signs indicate @github has fallen to the corporate hordes. Inventing middle-management, instituting mandatory office hours, catering to "premium" and "VIP" customers... The reason I think it'll fail quicker than other startups that did this is that GitHub's core technology is open source. Everyone can git commit. There will be a better github as soon as someone wants to make one. And that'll be about five seconds after github starts nickel-and-diming customers because their corporate managers think it'll increase Q3 revenue 1.5%. 

RIP Github.

**Comment by vram1980** [comment]
Just upgraded to the premium version. I don't think github is going anywhere any time soon.
